# Generated by Django 3.2.18 on 2023-08-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_stock_best_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
