# Generated by Django 3.2.18 on 2023-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_account_credittransaction_debittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='level',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
