# Generated by Django 3.2.18 on 2023-08-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_stock_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='level',
        ),
        migrations.CreateModel(
            name='Reorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.stock')),
            ],
        ),
    ]
