# Generated by Django 3.2.18 on 2023-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230827_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
